# Dependencies
highlighter: rouge

# Permalinks
#permalink:        pretty

# Setup
title: Elchead's site
tagline: "Sharing my thoughts with the world"
description: ""
#'The place where I share my thoughts and learning process'
author:
  name: "Adrian Stobbe"
include: [personal]
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Custom vars
version: 2.1.0
