# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Elchead's site
tagline:          ''
description:      'The place where I share my thoughts and learning process'
baseurl:          /
author:
  name:           'Adrian Stobbe'

gems: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
