name: hugo-latest-cd

on:
  push:
    branches:
      - main

env:
  TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  HUGO_ARGS: "--minify"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🔨 Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 🔧 Install tools
        run: |
          sudo apt install curl jq
          npm install postcss-cli autoprefixer
      - name: 🤵 Install Hugo
        run: |
          HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r '.tag_name')
          mkdir tmp/ && cd tmp/
          curl -sSL https://github.com/gohugoio/hugo/releases/download/${HUGO_VERSION}/hugo_extended_${HUGO_VERSION: -7}_Linux-64bit.tar.gz | tar -xvzf-
          sudo mv hugo /usr/local/bin/
          cd .. && rm -rf tmp/
          hugo version
      - name: 🧹 Clean site
        run: |
          if [ -d "docs" ]; then
            rm -rf docs/*
            cp CNAME ./docs
          fi
      - name: 🍳 Build site
        run: hugo ${HUGO_ARGS:-""} -d ${DEST:-"docs"}
      - name: 🚀 Deploy build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "🚀 Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git

## old version that deletes src files:
# name: Publish Site

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@master
#         with:
#           submodules: false
#       - name: Publish Site
#         uses: chabad360/hugo-gh-pages@master
#         with:
#           githubToken: ${{ secrets.PERSONAL_TOKEN }}
#           cname: elchead.me # Or anything else
#           repo: elchead/elchead.github.io
#           args: --gc --minify
#           # hugoVersion: extended_0.68.3
#           siteDir: /github/workspace/site
